### ISSUE TITLE
dispense function works error.

### ISSUE THREAD

**Issue by murdercdh** [joshuah/sol-redis-pool#5]
under windows7 x64 standard version. when I try to using client after acquire the client instance. The first time it throw the error like below.

Checking pool info after client destroyed:  0 1
Checking pool info after client destroyed:  1 1
TypeError: Cannot call method 'set' of undefined

at dispense (c:\xxxx\node_modules\sol-redis-pool\node_modules\generic-pool\lib\generic-pool.js:250:16)
    at Object.exports.Pool.me.acquire (c:\xxxx\node_modules\sol-redis-pool\node_modules\generic-pool\lib\generic-pool.js:319:5)
    at RedisPool.acquireClient [as acquire] (c:\xxxx\node_modules\sol-redis-pool\index.js:96:16)

**Comment by joshuah** [comment]
Unable to replicate the issue on Window 7 x64 Enterprise.
